fix: remove query param from manifest entry of img
adobe/aemscreens-offlineresources-generator pull request #10
Opened 2023-08-02 20:22 UTC by mchandak29

Manifest entry for Images contain query param, eg: `/content/screens/conference-rooms/Gather/media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=750&format=webply&optimize=medium`

As a result, players download low resolution images.

This changes removes the query param in path for Images.

2023-08-04 05:34 UTC, div8063 requested changes

2023-08-04 05:34 UTC, div8063 commented on src/createManifest.js
> +    const queryIndex = arr[index].indexOf('?');
Can be simplified to 
```suggestion
    arr[index] = arr[index].split('?')[0];
```

2023-08-04 05:34 UTC, div8063 commented on src/createManifest.js
> +      if (ManifestGenerator.isMedia(resourceSubPath)) {
Trying to understand why the ordering is reversed here.
Can you please explain?

2023-08-07 08:05 UTC, div8063 approved these changes

2023-08-07 08:09 UTC, merged

2023-08-07 13:26 UTC, habansal commented
@mchandak29 Where were these query params coming from?

2023-08-08 10:09 UTC, absarasw commented
`Where were these query params coming from?`
@mchandak29 , I think we should understand the scenarios first. May be later on there can be a use-case where the parameters are required.

2023-08-21 08:17 UTC, mchandak29 commented
> Where were these query params coming from?

For every media file, Franklin adds these query params in markup to optimise for smaller resolution displays. The default width is used as "750". So, If viewport width is not defined (when you programmatically fetch the markup) - it returns the image downsampled for default width.

```
<picture>
    <source type="image/webp" srcset="[./media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=2000&#x26;format=webply&#x26;optimize=medium](https://main--cec-screens--hlxscreens.hlx.live/content/screens/conference-rooms/media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=2000&#x26;format=webply&#x26;optimize=medium)" media="(min-width: 600px)">
    <source type="image/webp" srcset="[./media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=750&#x26;format=webply&#x26;optimize=medium](https://main--cec-screens--hlxscreens.hlx.live/content/screens/conference-rooms/media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=750&#x26;format=webply&#x26;optimize=medium)">
    <source type="image/jpeg" srcset="[./media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=2000&#x26;format=jpeg&#x26;optimize=medium](https://main--cec-screens--hlxscreens.hlx.live/content/screens/conference-rooms/media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=2000&#x26;format=jpeg&#x26;optimize=medium)" media="(min-width: 600px)">
    <img loading="lazy" alt="" src="[./media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=750&#x26;format=jpeg&#x26;optimize=medium](https://main--cec-screens--hlxscreens.hlx.live/content/screens/conference-rooms/media_1b41e396687e973df6f4e84d3e545c2dc888ce1e0.jpeg?width=750&format=jpeg&optimize=medium)" width="1280" height="720">
</picture>
```

We however display these images on a different(mostly larger viewport width) sizes. By removing the query params, player fetches the image in it's highest quality.

> May be later on there can be a use-case where the parameters are required.

since these params are only downsampling images(to save network bandwidth) keeping the same aspect ratio. I don't see any use-case for it right now. wdyt?

cc: @habansal @absarasw

2023-08-21 11:57 UTC, habansal commented
@mchandak29 Thanks for the explanation. Looks good!